"""Shared path helpers for WAAM."""

from __future__ import annotations

import os
import tempfile
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Optional


def _module_root() -> Path:
    return Path(__file__).resolve().parents[1]


def get_workspace_root() -> Path:
    """Return the root directory of the WAAM package."""
    return _module_root()


def _iter_output_candidates() -> Iterable[Path]:
    """Yield candidate directories in preference order for workbench artefacts."""
    # Prefer the package-local output directory so exports stay inside the addon.
    yield _module_root() / "output"

    env_keys = ("Waam_OUTPUT_DIR", "WAAM_OUTPUT_DIR")
    for key in env_keys:
        env_path = os.environ.get(key)
        if env_path:
            yield Path(env_path).expanduser()

    try:
        import FreeCAD as App  # type: ignore

        for getter in ("getUserCachePath", "getUserAppDataDir"):
            func = getattr(App, getter, None)
            if callable(func):
                try:
                    base = Path(func())
                except Exception:
                    continue
                if base:
                    yield (base / "Mod" / "WAAM").resolve()
                    yield (base / "WAAM").resolve()
    except Exception:
        pass

    appdata = os.environ.get("APPDATA")
    if appdata:
        yield Path(appdata) / "FreeCAD" / "WAAM"
    yield Path.home() / ".FreeCAD" / "WAAM"
    yield Path(tempfile.gettempdir()) / "waam_output"


@lru_cache(maxsize=1)
def _resolve_output_dir() -> Path:
    """Determine a writable directory for artefacts generated by the workbench."""
    seen = set()
    last_error = None
    for candidate in _iter_output_candidates():
        if candidate is None:
            continue
        candidate = candidate.expanduser()
        key = candidate.resolve()
        if key in seen:
            continue
        seen.add(key)
        try:
            candidate.mkdir(parents=True, exist_ok=True)
        except (PermissionError, OSError) as exc:
            last_error = exc
            continue
        if candidate.is_dir():
            return candidate
    if last_error:
        raise last_error
    fallback = _module_root() / "output"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback


def get_output_dir(create: bool = True) -> Path:
    """Return the path where workbench artefacts should be written."""
    path = _resolve_output_dir()
    if create and not path.exists():
        path.mkdir(parents=True, exist_ok=True)
    return path


def _artifact_path(
    subdir: str,
    filename: str,
    *,
    base_dir: Optional[Path | str] = None,
    prefer_existing: bool = True,
    create: bool = False,
) -> Path:
    """Resolve an artefact path under the output directory, optionally honoring legacy roots."""

    root = Path(base_dir).expanduser() if base_dir else get_output_dir()
    modern = root / subdir / filename
    legacy = root / filename

    if prefer_existing and not modern.exists() and legacy.exists():
        return legacy

    if create:
        modern.parent.mkdir(parents=True, exist_ok=True)
    return modern


def _output_root_for(path: Path) -> Path:
    """Infer the output root given a known artefact path."""
    parent = path.parent
    if parent.name in {"features", "operations_mesh", "nc_files"}:
        return parent.parent
    return parent


def get_features_path(
    base_dir: Optional[Path | str] = None, *, prefer_existing: bool = True, create: bool = False
) -> Path:
    """Default location of features.json (now under features/)."""
    return _artifact_path(
        "features",
        "features.json",
        base_dir=base_dir,
        prefer_existing=prefer_existing,
        create=create,
    )


def get_slice_plan_path(
    base_dir: Optional[Path | str] = None, *, prefer_existing: bool = True, create: bool = False
) -> Path:
    """Default location of waam_slice_plan.json (under operations_mesh/)."""
    return _artifact_path(
        "operations_mesh",
        "waam_slice_plan.json",
        base_dir=base_dir,
        prefer_existing=prefer_existing,
        create=create,
    )


def get_nc_output_path(
    base_dir: Optional[Path | str] = None, *, filename: str = "waam_baseline.nc", prefer_existing: bool = True, create: bool = False
) -> Path:
    """Default NC output path (under nc_files/)."""
    return _artifact_path(
        "nc_files",
        filename,
        base_dir=base_dir,
        prefer_existing=prefer_existing,
        create=create,
    )


__all__ = [
    "get_features_path",
    "get_nc_output_path",
    "get_slice_plan_path",
    "get_output_dir",
    "get_workspace_root",
    "_output_root_for",
]
